### ISSUE TITLE
Improving error messages

### ISSUE THREAD

**Issue by DanPurdy** [DanPurdy/linter-sass-lint#16]
Looking to improve the format of error messages, scenarios such as executable doesn't exist and parse errors from sass-lint.

Will update this issue as I move through them.

**Comment by noderat** [comment]
Should also add an option not to try and lint if there isn't a .sass-lint.yml file present in the current project directory. (See [AtomLinter/linter-jscs](https://github.com/AtomLinter/linter-jscs) options for example)

**Comment by DanPurdy** [comment]
Thanks @noderat I should be back working on this soon, will get this out as a priority

**Comment by DanPurdy** [comment]
Hi @noderat sorry this has taken so long, I've just released v0.5.0 which includes an option to disable linting if a config file is not present in the project root AND not specified in the config path option. 

This repository has also moved over to the AtomLinter organisation so let me know if you have any issues updating as the package itself was unpublished and republished.

Thanks!

https://github.com/AtomLinter/linter-sass-lint
