### ISSUE TITLE
Atom crashes on save

### ISSUE THREAD

**Issue by glaucomorais** [DanPurdy/linter-sass-lint#18]
Everytime that I save a scss file, Atom crashes and I need to close the window.
I tried with every single package disable/enable one at time and yours seems to be the issue.

I don't know how to get a crash log (yet), but I'm here to help. Give some directions to help and I'll do with pleasure.

**Comment by DanPurdy** [comment]
Hi @glaucomorais I'm sorry to hear this, have you tried reinstalling? Can you give me the atom version number and the linter-sass-lint version number and the atom linter version number too. Thanks

**Comment by DanPurdy** [comment]
Closing this for lack of info. I've run it against the latest beta too and not seeing any crashing..
