### ISSUE TITLE
Option to only lint when a .sass-lint.yml file is in the project directory

### ISSUE THREAD

**Issue by FabianMeul** [DanPurdy/linter-sass-lint#19]
Is it possible to add an option to only execute the linting when a valid .sass-lint.yml file in found in the project directory?

I'm receiving errors on save on how "No file is found". (And this is correct, there is none.)

Thx!

**Comment by DanPurdy** [comment]
No problem, should be back working on this and sass-lint soon, thanks for the suggestion @FabianMeul

**Comment by DanPurdy** [comment]
Actually just remembered this was already asked for in #16 too

**Comment by FabianMeul** [comment]
Aha, missed that one! Sorry about that.

**Comment by DanPurdy** [comment]
No problem, will get it out soon.

**Comment by DanPurdy** [comment]
@FabianMeul sorry this took so long but this is now done and an option in v0.5.0. This repository is no longer in use as it's been moved over to the AtomLinter organisation. Could you let me know if the update doesn't show up correctly in your Atom package manager?

Thanks! Let me know at the new repository location if you have any issues moving forward.

https://github.com/AtomLinter/linter-sass-lint
