### ISSUE TITLE
Parsing error: !global

### ISSUE THREAD

**Issue by mikegleasonjr** [DanPurdy/linter-sass-lint#20]
I don't know in the dependency chain where I should file this bug but this valid syntax gives an error:

``` scss
$color: #fff !global;
```

`Parsing error: Please check validity of the block.`

**Comment by DanPurdy** [comment]
Hi @mikegleasonjr, yeah, this is something we're waiting for our AST to update in `sass-lint` for. 

You can find the issue [here](https://github.com/sasstools/sass-lint/issues/305)

I'm afraid there's not much we can do until gonzales-pe becomes a bit more stable.. :cry:
