### ISSUE TITLE
Repeated configuration error

### ISSUE THREAD

**Issue by abea** [DanPurdy/linter-sass-lint#21]
```
TypeError: Invalid configuration: private method 'load' called for Psych:Module
  at /Users/[username]/.atom/packages/linter-scss-lint/lib/init.coffee:56:23
```

I'm getting this error on any Sass file updating now. The only think I can think of is that something in my Homebrew update changed. the Atom emmet and pigment packages also updated today, if that might matter.

**Comment by DanPurdy** [comment]
Hi I think you might have the wrong repo, looks like you're using `linter-scss-lint` which is the plugin for `scss-lint` built in ruby.

This repo is for `linter-sass-lint` which is the plugin for `sass-lint` built in javascript..

You can find linter-scss-lint [here](https://github.com/AtomLinter/linter-scss-lint)
and if you want to do away with ruby and move to sass-lint you can find that [here](https://github.com/sasstools/sass-lint)

**Comment by abea** [comment]
Sorry about that.

**Comment by DanPurdy** [comment]
No problem
