### ISSUE TITLE
join us

### ISSUE THREAD

**Issue by hd-deman** [DanPurdy/linter-sass-lint#27]
You can transfer it to the AtomLinter org if you'd like. You'll still be the maintainer.
The sooner you do it, the less the statistics of downloads you will lose)
flow:
1. run `apm unpublish linter-sass-lint` command to unpublish package
2. move repo to AtomLInter org (you will be an administrator)
3. fix repo url in package.json
4. publish again

This allows us to more easily keep track of linters that need to be fixed after major updates to the core linter. Additionally, by pulling you into the organization it allows us to keep linter creators up to date with changes and plans people have to advance the project. Lastly it has been a good tool when people have issues with the linters where users can rely on a larger stable of developers to help them with their issues on any given linter.

welcome to the biggest atom package community ::)

**Comment by DanPurdy** [comment]
Hi @hd-deman thanks for reaching out. I've accepted the invite, I'll hopefully get a chance to do move it over tomorrow, busy day today.

Thanks again!

**Comment by DanPurdy** [comment]
@hd-deman steelbrain and i didn't manage to get this repository transferred over fully due to some admin issues so we just pushed a clone up for now. Everything else is migrated. Thanks!
